/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Controller;
import FormandAdgang.Member;
import javax.swing.JFrame;

/**
 *
 * @author Emil PC
 */
public class TGUIRegisterResult extends javax.swing.JFrame {

    
    /**
     * Creates new form TGUIRegisterResult
     */
    
    private TGUI tGUI;
    
    public TGUIRegisterResult(JFrame fGui) {
        initComponents();
       // this.tGUI = (TGUI) fGui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        butterflyClick = new javax.swing.JCheckBox();
        backstrokeClick = new javax.swing.JCheckBox();
        freeClick = new javax.swing.JCheckBox();
        cheststrokeClick = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        phonenumberText = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regResButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JToggleButton();
        menuButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butterflyClick.setText("Butterfly");
        butterflyClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterflyClickActionPerformed(evt);
            }
        });

        backstrokeClick.setText("Backstroke");
        backstrokeClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backstrokeClickActionPerformed(evt);
            }
        });

        freeClick.setText("Free");
        freeClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeClickActionPerformed(evt);
            }
        });

        cheststrokeClick.setText("Cheststroke");
        cheststrokeClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheststrokeClickActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        phonenumberText.setText("Phonenumber");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Time in seconds");

        jLabel3.setText("Diciplin");

<<<<<<< HEAD
        regResButton.setText("Register result");

        clearButton.setText("Clear");
=======
        jToggleButton1.setText("Register result");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Clear");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
>>>>>>> 05a257f7226812283fb817620e1d4e835587ee2c

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phonenumberText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butterflyClick)
                                    .addComponent(freeClick))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cheststrokeClick)
                                    .addComponent(backstrokeClick)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regResButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumberText)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regResButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backstrokeClick)
                    .addComponent(butterflyClick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freeClick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheststrokeClick)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backstrokeClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backstrokeClickActionPerformed
        if (butterflyClick.isSelected()) {
            butterflyClick.doClick();
        }
        if (freeClick.isSelected()) {
            freeClick.doClick();
        }
        if (cheststrokeClick.isSelected()) {
            cheststrokeClick.doClick();
        }
    }//GEN-LAST:event_backstrokeClickActionPerformed

    private void butterflyClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterflyClickActionPerformed
        if (backstrokeClick.isSelected()) {
            backstrokeClick.doClick();
        }
        if (freeClick.isSelected()) {
            freeClick.doClick();
        }
        if (cheststrokeClick.isSelected()) {
            cheststrokeClick.doClick();
        }
    }//GEN-LAST:event_butterflyClickActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
       // this.setVisible(false);
       // tGUI.setVisible(true);
        
    }//GEN-LAST:event_menuButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String phone = jTextField1.getText();
        Controller c = new Controller();
        Member member = c.getMember(phone);
        String discipline = "";
        
        if (freeClick.isSelected()) {
            discipline = "Free";
        }
        if (backstrokeClick.isSelected()) {
            discipline = "Backstroke";
        }
        if (butterflyClick.isSelected()) {
            discipline = "Butterfly";
        }
        if (cheststrokeClick.isSelected()) {
            discipline = "Cheststroke";
        }
        
        int time = Integer.parseInt(jTextField2.getText());
        c.registerResult(member, discipline, time);
        
        jToggleButton2.doClick();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void freeClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeClickActionPerformed
        if (backstrokeClick.isSelected()) {
            backstrokeClick.doClick();
        }
        if (butterflyClick.isSelected()) {
            butterflyClick.doClick();
        }
        if (cheststrokeClick.isSelected()) {
            cheststrokeClick.doClick();
        }
    }//GEN-LAST:event_freeClickActionPerformed

    private void cheststrokeClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheststrokeClickActionPerformed
        if (backstrokeClick.isSelected()) {
            backstrokeClick.doClick();
        }
        if (butterflyClick.isSelected()) {
            butterflyClick.doClick();
        }
        if (freeClick.isSelected()) {
            freeClick.doClick();
        }
    }//GEN-LAST:event_cheststrokeClickActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (backstrokeClick.isSelected()) {
            backstrokeClick.doClick();
        }
        if (butterflyClick.isSelected()) {
            butterflyClick.doClick();
        }
        if (freeClick.isSelected()) {
            freeClick.doClick();
        }
        if (cheststrokeClick.isSelected()) {
            cheststrokeClick.doClick();
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TGUIRegisterResult().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backstrokeClick;
    private javax.swing.JCheckBox butterflyClick;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cheststrokeClick;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JCheckBox freeClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton menuButton;
    private javax.swing.JLabel phonenumberText;
    private javax.swing.JToggleButton regResButton;
    // End of variables declaration//GEN-END:variables
}
