/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Controller.Controller;
import Trainer.Result;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Emil PC
 */
public class TGUIShowResults extends javax.swing.JFrame {
    
    private boolean t1 = false;
    private boolean t2 = false;
    private TGUI tgui;

    /** Creates new form TGUIShowResults */
    public TGUIShowResults(JFrame tgui) {
        initComponents();
        this.tgui = (TGUI) tgui;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butterflyButton = new javax.swing.JToggleButton();
        backstrokeButton = new javax.swing.JToggleButton();
        cheststrokeButton = new javax.swing.JToggleButton();
        freeButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jToggleButton5 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        juniorCheck = new javax.swing.JCheckBox();
        seniorCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butterflyButton.setText("Butterfly results");
        butterflyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterflyButtonActionPerformed(evt);
            }
        });

        backstrokeButton.setText("Backstroke results");
        backstrokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backstrokeButtonActionPerformed(evt);
            }
        });

        cheststrokeButton.setText("Cheststroke results");
        cheststrokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheststrokeButtonActionPerformed(evt);
            }
        });

        freeButton.setText("Free results");
        freeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jToggleButton5.setText("Clear");

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        juniorCheck.setText("Junior");
        juniorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniorCheckActionPerformed(evt);
            }
        });

        seniorCheck.setText("Senior");
        seniorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butterflyButton)
                                .addGap(18, 18, 18)
                                .addComponent(backstrokeButton)
                                .addGap(18, 18, 18)
                                .addComponent(cheststrokeButton)
                                .addGap(18, 18, 18)
                                .addComponent(freeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(juniorCheck)
                                    .addComponent(seniorCheck))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butterflyButton)
                    .addComponent(backstrokeButton)
                    .addComponent(cheststrokeButton)
                    .addComponent(freeButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(juniorCheck)
                        .addGap(18, 18, 18)
                        .addComponent(seniorCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton5)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juniorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniorCheckActionPerformed
        if (seniorCheck.isSelected()) {
            seniorCheck.doClick();
        }
    }//GEN-LAST:event_juniorCheckActionPerformed

    private void seniorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorCheckActionPerformed
        if (juniorCheck.isSelected()) {
            juniorCheck.doClick();
        }
    }//GEN-LAST:event_seniorCheckActionPerformed

    private void butterflyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterflyButtonActionPerformed
        Controller c = new Controller();
        ArrayList<Result> results = new ArrayList();
        if (juniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Butterfly", c.getAllJuniorResults());
        } else if (seniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Butterfly", c.getAllSeniorResults());
        }
        String text = "";
        
        for (int i = 0; i < results.size(); ++i) {
            text += results.get(i) + "\n";
        }
        
        textArea.setText(text);
        
    }//GEN-LAST:event_butterflyButtonActionPerformed

    private void backstrokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backstrokeButtonActionPerformed
        Controller c = new Controller();
        ArrayList<Result> results = new ArrayList();
        if (juniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Backstroke", c.getAllJuniorResults());
        } else if (seniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Backstroke", c.getAllSeniorResults());
        }
        String text = "";
        
        for (int i = 0; i < results.size(); ++i) {
            text += results.get(i) + "\n";
        }
        
        textArea.setText(text);
    }//GEN-LAST:event_backstrokeButtonActionPerformed

    private void cheststrokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheststrokeButtonActionPerformed
        Controller c = new Controller();
        ArrayList<Result> results = new ArrayList();
        if (juniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Cheststroke", c.getAllJuniorResults());
        } else if (seniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Cheststroke", c.getAllSeniorResults());
        }
        String text = "";
        
        for (int i = 0; i < results.size(); ++i) {
            text += results.get(i) + "\n";
        }
        
        textArea.setText(text);
    }//GEN-LAST:event_cheststrokeButtonActionPerformed

    private void freeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeButtonActionPerformed
        Controller c = new Controller();
        ArrayList<Result> results = new ArrayList();
        if (juniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Free", c.getAllJuniorResults());
        } else if (seniorCheck.isSelected()) {
            results = c.getDisciplineTop5("Free", c.getAllSeniorResults());
        }
        String text = "";
        
        for (int i = 0; i < results.size(); ++i) {
            text += results.get(i) + "\n";
        }
        
        textArea.setText(text);
    }//GEN-LAST:event_freeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        tgui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backstrokeButton;
    private javax.swing.JToggleButton butterflyButton;
    private javax.swing.JToggleButton cheststrokeButton;
    private javax.swing.JToggleButton freeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JCheckBox juniorCheck;
    private javax.swing.JCheckBox seniorCheck;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
