/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Controller;
import FormandAdgang.Member;
import javax.swing.JFrame;

/**
 *
 * @author ahmed
 */
public class TGUIRegisterResults extends javax.swing.JFrame {

    /**
     * Creates new form TGUIRegisterResults
     */
    private TGUI tGUI;
    
    public TGUIRegisterResults(JFrame tGui) {
        initComponents();
        this.tGUI = (TGUI) tGui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butterflyCheckBox = new javax.swing.JCheckBox();
        backstrokeCheckBox = new javax.swing.JCheckBox();
        freeCheckBox = new javax.swing.JCheckBox();
        chestStrokeCheckBox = new javax.swing.JCheckBox();
        resultButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        timeInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Phone number");

        butterflyCheckBox.setText("Butterfly");
        butterflyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterflyCheckBoxActionPerformed(evt);
            }
        });

        backstrokeCheckBox.setText("Backstroke");
        backstrokeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backstrokeCheckBoxActionPerformed(evt);
            }
        });

        freeCheckBox.setText("Free");
        freeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeCheckBoxActionPerformed(evt);
            }
        });

        chestStrokeCheckBox.setText("Cheststroke");
        chestStrokeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chestStrokeCheckBoxActionPerformed(evt);
            }
        });

        resultButton.setText("Register result");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Time in seconds");

        timeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setText("Register Results");

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butterflyCheckBox)
                            .addComponent(freeCheckBox))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backstrokeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chestStrokeCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(phoneInput))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timeInput)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butterflyCheckBox)
                            .addComponent(backstrokeCheckBox))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(freeCheckBox)
                            .addComponent(chestStrokeCheckBox)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resultButton)
                        .addGap(28, 28, 28)
                        .addComponent(clearButton)))
                .addGap(13, 13, 13)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        String phone = phoneInput.getText();
        Controller c = new Controller();
        Member member = c.getMember(phone);
        String discipline = "";
        
        if (freeCheckBox.isSelected()) {
            discipline = "Free";
        }
        if (backstrokeCheckBox.isSelected()) {
            discipline = "Backstroke";
        }
        if (butterflyCheckBox.isSelected()) {
            discipline = "Butterfly";
        }
        if (chestStrokeCheckBox.isSelected()) {
            discipline = "Cheststroke";
        }
        
        int time = Integer.parseInt(timeInput.getText());
        c.registerResult(member, discipline, time);
        
        clearButton.doClick();
        
    }//GEN-LAST:event_resultButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if (backstrokeCheckBox.isSelected()) {
            backstrokeCheckBox.doClick();
        }
        if (butterflyCheckBox.isSelected()) {
            butterflyCheckBox.doClick();
        }
        if (freeCheckBox.isSelected()) {
            freeCheckBox.doClick();
        }
        if (chestStrokeCheckBox.isSelected()) {
            chestStrokeCheckBox.doClick();
        }
        
        phoneInput.setText("");
        timeInput.setText("");
     
    }//GEN-LAST:event_clearButtonActionPerformed

    private void butterflyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterflyCheckBoxActionPerformed
        if(backstrokeCheckBox.isSelected()){
            backstrokeCheckBox.doClick();
        }
        if(chestStrokeCheckBox.isSelected()){
            chestStrokeCheckBox.doClick();
        }
        if(freeCheckBox.isSelected()){
            freeCheckBox.doClick();
        }
        
    }//GEN-LAST:event_butterflyCheckBoxActionPerformed

    private void backstrokeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backstrokeCheckBoxActionPerformed
        if(butterflyCheckBox.isSelected()){
            butterflyCheckBox.doClick();
        }
        if(chestStrokeCheckBox.isSelected()){
            chestStrokeCheckBox.doClick();
        }
        if(freeCheckBox.isSelected()){
            freeCheckBox.doClick();
        }
        
    }//GEN-LAST:event_backstrokeCheckBoxActionPerformed

    private void chestStrokeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestStrokeCheckBoxActionPerformed
        if(butterflyCheckBox.isSelected()){
            butterflyCheckBox.doClick();
        }
        if(backstrokeCheckBox.isSelected()){
            backstrokeCheckBox.doClick();
        }
        if(freeCheckBox.isSelected()){
            freeCheckBox.doClick();
        }
        
    }//GEN-LAST:event_chestStrokeCheckBoxActionPerformed

    private void freeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeCheckBoxActionPerformed
        if(butterflyCheckBox.isSelected()){
            butterflyCheckBox.doClick();
        }
        if(chestStrokeCheckBox.isSelected()){
            chestStrokeCheckBox.doClick();
        }
        if(backstrokeCheckBox.isSelected()){
            backstrokeCheckBox.doClick();
        }
        
    }//GEN-LAST:event_freeCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        tGUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeInputActionPerformed

    /**
     * @param delete or comment out the manins of the GUI to make them connect
     * with themselfs wihout screwning up bt makning new instanse of the GUI.
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TGUIRegisterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TGUIRegisterResults().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backstrokeCheckBox;
    private javax.swing.JCheckBox butterflyCheckBox;
    private javax.swing.JCheckBox chestStrokeCheckBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JCheckBox freeCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JButton resultButton;
    private javax.swing.JTextField timeInput;
    // End of variables declaration//GEN-END:variables
}
